### ISSUE TITLE
Error thrown titleizing '_id'

### ISSUE THREAD

**Issue by gmsewell6** [pksunkara/inflect#15]
An error is thrown when titlizing '_id'

```
$ node
> require('i')().titleize('_id')
TypeError: Cannot call method 'toUpperCase' of undefined
    at Object.module.exports.string.capitalize (/node_modules/i/lib/util.js:113:22)
    at Object.inflect.humanize (/node_modules/i/lib/methods.js:195:22)
    at Object.inflect.titleize (/node_modules/i/lib/methods.js:207:18)
    at repl:1:17
```

another oddness: titleizing '__id' results in a single space

```
$ node
> require('i')().titleize('__id')
' '
```

**Comment by pksunkara** [comment]
Which node.js version is this?

**Comment by gmsewell6** [comment]
```
$ node --version
v0.10.40
```
